'use strict';

var gulp = require('gulp'),
    ts = require('gulp-typescript'),
    tslint = require('gulp-tslint'),
    es = require('event-stream'),
    sourcemaps = require('gulp-sourcemaps'),
    del = require('del'),
    concat = require('gulp-concat');

gulp.task('ts-compile', ['ts-lint'], function() {
    var tsProject = ts.createProject('tsconfig.json');
        var tsStream = gulp.src(['app/**/*.ts','!app/bower_components/**/*']).pipe(ts(tsProject));

    es.merge(
        tsStream.dts.pipe(gulp.dest('target/tmp/js')),
        tsStream.js
            .pipe(concat('target/tmp/main.js'))
            .pipe(gulp.dest('target/tmp/js'))
    );
});

/**
 * lint all TypeScript files.
 */
gulp.task('ts-lint', function () {
    return gulp.src(['app/**/*.ts', '!app/bower_components/**/*'])
        .pipe(tslint())
        .pipe(tslint.report('prose'));
});

/**
 * Remove all generated JavaScript files from TypeScript compilation.
 */
gulp.task('ts-clean', function (cb) {
    var typeScriptGenFiles = [
        'target/tmp/js/**/*.js',    // path to all autogenerated JS files
        'target/tmp/js/**/*.js.map' // path to all autogenerated sourcemap files
    ];

    del(typeScriptGenFiles, cb);
});
